name: Python Hello World

# Triggers the workflow on push or pull request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Run the Python script
      - name: Run test.py
        run: python test.py
